//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multigroup.Repositories.Menu.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedures() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multigroup.Repositories.Menu.Resources.StoredProcedures", typeof(StoredProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponent_Delete.
        /// </summary>
        internal static string pub_MenuComponent_Delete {
            get {
                return ResourceManager.GetString("pub_MenuComponent_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponent_Get.
        /// </summary>
        internal static string pub_MenuComponent_Get {
            get {
                return ResourceManager.GetString("pub_MenuComponent_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponent_GetList.
        /// </summary>
        internal static string pub_MenuComponent_GetList {
            get {
                return ResourceManager.GetString("pub_MenuComponent_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponent_Insert.
        /// </summary>
        internal static string pub_MenuComponent_Insert {
            get {
                return ResourceManager.GetString("pub_MenuComponent_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponent_Update.
        /// </summary>
        internal static string pub_MenuComponent_Update {
            get {
                return ResourceManager.GetString("pub_MenuComponent_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponentPage_Delete.
        /// </summary>
        internal static string pub_MenuComponentPage_Delete {
            get {
                return ResourceManager.GetString("pub_MenuComponentPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponentPage_Get.
        /// </summary>
        internal static string pub_MenuComponentPage_Get {
            get {
                return ResourceManager.GetString("pub_MenuComponentPage_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponentPage_GetList.
        /// </summary>
        internal static string pub_MenuComponentPage_GetList {
            get {
                return ResourceManager.GetString("pub_MenuComponentPage_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponentPage_Insert.
        /// </summary>
        internal static string pub_MenuComponentPage_Insert {
            get {
                return ResourceManager.GetString("pub_MenuComponentPage_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponentPage_Update.
        /// </summary>
        internal static string pub_MenuComponentPage_Update {
            get {
                return ResourceManager.GetString("pub_MenuComponentPage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponentRole_Delete.
        /// </summary>
        internal static string pub_MenuComponentRole_Delete {
            get {
                return ResourceManager.GetString("pub_MenuComponentRole_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_MenuComponentRole_Insert.
        /// </summary>
        internal static string pub_MenuComponentRole_Insert {
            get {
                return ResourceManager.GetString("pub_MenuComponentRole_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_TestApplicationRange_Insert.
        /// </summary>
        internal static string pub_TestApplicationRange_Insert {
            get {
                return ResourceManager.GetString("pub_TestApplicationRange_Insert", resourceCulture);
            }
        }
    }
}
