//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multigroup.Repositories.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedures() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multigroup.Repositories.Shared.Resources.StoredProcedures", typeof(StoredProcedures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Rol_Get.
        /// </summary>
        internal static string pub_Rol_Get {
            get {
                return ResourceManager.GetString("pub_Rol_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Rol_GetList.
        /// </summary>
        internal static string pub_Rol_GetList {
            get {
                return ResourceManager.GetString("pub_Rol_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Roles_GetList.
        /// </summary>
        internal static string pub_Roles_GetList {
            get {
                return ResourceManager.GetString("pub_Roles_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Sucursal_Delete.
        /// </summary>
        internal static string pub_Sucursal_Delete {
            get {
                return ResourceManager.GetString("pub_Sucursal_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Sucursal_Get.
        /// </summary>
        internal static string pub_Sucursal_Get {
            get {
                return ResourceManager.GetString("pub_Sucursal_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Sucursal_GetList.
        /// </summary>
        internal static string pub_Sucursal_GetList {
            get {
                return ResourceManager.GetString("pub_Sucursal_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Sucursal_Insert.
        /// </summary>
        internal static string pub_Sucursal_Insert {
            get {
                return ResourceManager.GetString("pub_Sucursal_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_Sucursal_Update.
        /// </summary>
        internal static string pub_Sucursal_Update {
            get {
                return ResourceManager.GetString("pub_Sucursal_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_SucursalSummary_GetList.
        /// </summary>
        internal static string pub_SucursalSummary_GetList {
            get {
                return ResourceManager.GetString("pub_SucursalSummary_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_SucursalxEmpleado_Delete.
        /// </summary>
        internal static string pub_SucursalxEmpleado_Delete {
            get {
                return ResourceManager.GetString("pub_SucursalxEmpleado_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_SucursalxEmpleado_Get.
        /// </summary>
        internal static string pub_SucursalxEmpleado_Get {
            get {
                return ResourceManager.GetString("pub_SucursalxEmpleado_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_SucursalxEmpleado_Update.
        /// </summary>
        internal static string pub_SucursalxEmpleado_Update {
            get {
                return ResourceManager.GetString("pub_SucursalxEmpleado_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_User_Get.
        /// </summary>
        internal static string pub_User_Get {
            get {
                return ResourceManager.GetString("pub_User_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_User_GetList.
        /// </summary>
        internal static string pub_User_GetList {
            get {
                return ResourceManager.GetString("pub_User_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_User_Insert.
        /// </summary>
        internal static string pub_User_Insert {
            get {
                return ResourceManager.GetString("pub_User_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_User_Login.
        /// </summary>
        internal static string pub_User_Login {
            get {
                return ResourceManager.GetString("pub_User_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_User_Update.
        /// </summary>
        internal static string pub_User_Update {
            get {
                return ResourceManager.GetString("pub_User_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_UserByEmail_Get.
        /// </summary>
        internal static string pub_UserByEmail_Get {
            get {
                return ResourceManager.GetString("pub_UserByEmail_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_UserByUserName_Get.
        /// </summary>
        internal static string pub_UserByUserName_Get {
            get {
                return ResourceManager.GetString("pub_UserByUserName_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_UserCountry_Get.
        /// </summary>
        internal static string pub_UserCountry_Get {
            get {
                return ResourceManager.GetString("pub_UserCountry_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_UserRoles_Delete.
        /// </summary>
        internal static string pub_UserRoles_Delete {
            get {
                return ResourceManager.GetString("pub_UserRoles_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_UserRoles_GetList.
        /// </summary>
        internal static string pub_UserRoles_GetList {
            get {
                return ResourceManager.GetString("pub_UserRoles_GetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pub_UserRoles_Insert.
        /// </summary>
        internal static string pub_UserRoles_Insert {
            get {
                return ResourceManager.GetString("pub_UserRoles_Insert", resourceCulture);
            }
        }
    }
}
