using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Multigroup.Common.Logging
{
    public enum AuditLogType
    {
        AnalysisFileService,
        UserService,
        WidgetService,
        SampleService,
        Analysis,
        ActionPlanService,
        PdfActionPlanService,
        NotificationService,
        ComponentService,
        XlsDataService,
        DownloadEvent,
        DownloadTrend,
        DownloadEventVL,
        DownloadCycleReport,
        Health,
        DownloadSMU,
        DownloadSMUVL,
        PayLoad,
        PayLoadLimits,
        SOSDownload,
        SosEquipmentDownload,
        AnalysisService,
        DataAnalysisService,
        RoutineStatusDataService,
        HotSheetService,
        WorkLoadService,
        DownloadEngineVL,
        ComponentStatusLog,
        TrendRebuild,
        AlarmService,
        AlertLoad,
        TestApplicationService,
        EquipmentService,
        FMfmeaService,
        SiteService,
        CustomerService,
        RoleService,
        RoutineService,
        TestService,
        AccountCotroller,
        AnalysisFileController,
        MappingService,
        GeneralInspectionService,
        DataProcess,
        MenuService,
        MaintenanceIntervalController,
        News,
        PivotConfiguation,
        RoutineDataImageService,
        RoutineDataService,
        RoutineLoadController,
        AaiController,
        HotSheetController,
        GeneralReportController,
        GeneralReportService,
    }
}
